//! Generates an embedded catalog of the vardiff-sim scenario TOMLs so the
//! binary can list and load them with no filesystem access (hub session
//! children run with no reliable cwd). Emits `scenario_catalog.rs` with a
//! `&[(name, toml_contents)]` slice, rebuilt whenever a scenario changes.

use std::{env, fs, path::Path};

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("scenarios");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(read) = fs::read_dir(&dir) {
        for e in read.flatten() {
            let path = e.path();
            if path.extension().and_then(|s| s.to_str()) == Some("toml") {
                let name = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or_default()
                    .to_string();
                println!("cargo:rerun-if-changed={}", path.display());
                entries.push((name, path.to_string_lossy().into_owned()));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::from(
        "// @generated by build.rs — embedded scenario catalog.\n\
         /// (name, TOML contents) for every bundled scenario, sorted by name.\n\
         pub static SCENARIO_CATALOG: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &entries {
        src.push_str(&format!(
            "    ({name:?}, include_str!({path:?})),\n"
        ));
    }
    src.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("scenario_catalog.rs");
    fs::write(&out, src).expect("write scenario catalog");
}
