name: Semver Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semver-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install cargo-semver-checks
        run: cargo install cargo-semver-checks --version 0.37.0 --locked

      #  TODO: Add semver checks for stratum-apps workspace when it is published
      #- name: Run semver checks for stratum-apps workspace
      #  working-directory: stratum-apps
      #  run: cargo semver-checks --all-features

      # TODO: Add semver checks for pool applications workspace when JDS is published
      #- name: Run semver checks for pool applications workspace
      #  working-directory: pool-apps
      #  run: cargo semver-checks

      # TODO: Add semver checks for miner applications workspace when JDC is published
      #- name: Run semver checks for miner applications workspace
      #  working-directory: miner-apps
      #  run: cargo semver-checks